language: python
python:
  - "3.6.3"
services:
  - docker
before_install:
 - set -e

notifications:
  email:
    on_success: change
    on_failure: change

env:
 - RELEASE=docker_user
 #- RELEASE=docker_user DO_IMPORT=1

# https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
# sudo: required
# dist: trusty
# group: deprecated-2017Q4
 
install:
 - sudo apt install opus-tools
 - pip install -r requirements.txt

# command to run tests
script:
 - set -e
 
 - git clone https://github.com/stts-se/pronlex.git
 - cd pronlex
 - git checkout $RELEASE || echo "No such release for pronlex. Using master."
 - cd ..
 - git clone https://github.com/stts-se/marytts.git
 - cd marytts
 - git checkout $RELEASE || echo "No such release for marytts. Using master."
 - cd ..
 
 - docker build pronlex -t pronlex --build-arg RELEASE=$RELEASE
 - docker run -v /wikispeech/appdir:/wikispeech/appdir -p 8787:8787 -t pronlex /wikispeech/pronlex/bin/setup /wikispeech/appdir
 
 - |
   if [ -v DO_IMPORT ]; then
     docker run -v /wikispeech/appdir:/wikispeech/appdir -p 8787:8787 -t pronlex /wikispeech/pronlex/bin/import_all /wikispeech/appdir /wikispeech/appdir $RELEASE || docker run -v /wikispeech/appdir:/wikispeech/appdir -p 8787:8787 -t pronlex /wikispeech/pronlex/bin/import_all /wikispeech/appdir /wikispeech/appdir master
   fi
 
 - docker build marytts -t marytts --build-arg RELEASE=$RELEASE
 - docker run -v /wikispeech/appdir:/wikispeech/appdir -p 8787:8787 -t pronlex &
 - export pronlex_pid=$!
 - echo "pronlex started with pid $pronlex_pid"
 - sleep 20
 
 - docker run -p 59125:59125 -t marytts &
 - export marytts_pid=$!
 - echo "marytts started with pid $marytts_pid"
 - sleep 20
 
 - python3 bin/wikispeech docker/config/travis.conf &
 - export wikispeech_pid=$!  
 - echo "wikispeech started with pid $wikispeech_pid"
 - sleep 20
 
 - sh .travis/exit_server_and_fail_if_not_running.sh wikispeech $wikispeech_pid
 - sh .travis/exit_server_and_fail_if_not_running.sh marytts $marytts_pid
 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pronlex_pid
 
 - docker build . -t wikispeech
