language: python
python:
  - "3.5.3"
services:
  - docker
before_install:
 # fail on any non-zero exit value
 - set -e
 
install:
 - sudo apt install opus-tools
 - pip install -r requirements.txt
 - docker build https://github.com/stts-se/pronlex.git -t pronlex
 - docker build https://github.com/HannaLindgren/marytts.git -t marytts
 
before_script:
 - docker run -v /tmp/appdir:/appdir -p 8787:8787 -t pronlex setup /tmp/appdir
 - docker run -v /tmp/appdir:/appdir -p 8787:8787 -t pronlex &
 - export pronlex_pid=$!
 - echo "pronlex running on pid $pronlex_pid"
 - sleep 20
 - docker run -p 59125:59125 -t marytts &
 - export marytts_pid=$!
 - echo "marytts running on pid $marytts_pid"
 - sleep 20
  
# command to run tests
script:
 - python3 bin/wikispeech docker/config/travis.conf &
 - export wikispeech_pid=$!  
 - echo "wikispeech running on pid $wikispeech_pid"
 - sleep 20
 - sh .travis/exit_server_and_fail_if_not_running.sh wikispeech $wikispeech_pid
 - sh .travis/exit_server_and_fail_if_not_running.sh marytts $marytts_pid
 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pronlex_pid
 
