language: python
python:
  - "3.6.3"
services:
  - docker
before_install:
 # fail on any non-zero exit value
 - set -e

# https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
# sudo: required
# dist: trusty
# group: deprecated-2017Q4
 
install:
 - sudo apt install opus-tools
 - pip install -r requirements.txt
 - cd .travis
 - docker build https://github.com/stts-se/pronlex.git#docker_update -t pronlex:travis --build-arg RELEASE=docker_update
 - docker build https://github.com/stts-se/marytts.git#$docker_update -t marytts:travis --build-arg RELEASE=docker_update

# command to run tests
script:
 - set -e
 - docker run -v /appdir:/appdir -p 8787:8787 -t pronlex:travis /wikispeech/pronlex/bin/setup /appdir
 - docker run -v /appdir:/appdir -p 8787:8787 -t pronlex:travis &
 - export pronlex_pid=$!
 - echo "pronlex running with pid $pronlex_pid"
 - sleep 20
 - docker run -p 59125:59125 -t marytts:travis &
 - export marytts_pid=$!
 - echo "marytts running with pid $marytts_pid"
 - sleep 20
 - python3 bin/wikispeech docker/config/travis.conf &
 - export wikispeech_pid=$!  
 - echo "wikispeech running with pid $wikispeech_pid"
 - sleep 20
 - sh .travis/exit_server_and_fail_if_not_running.sh wikispeech $wikispeech_pid
 - sh .travis/exit_server_and_fail_if_not_running.sh marytts $marytts_pid
 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pronlex_pid
