language: python
python:
  - "3.5.3"
services:
  - docker
before_install:
 # fail on any non-zero exit value
 - set -e

# https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
# sudo: required
# dist: trusty
group: deprecated-2017Q4
 
install:
 - sudo apt install opus-tools
 - pip install -r requirements.txt

# command to run tests
script:
 - docker build https://github.com/stts-se/pronlex.git -t pronlex
 - docker build https://github.com/HannaLindgren/marytts.git -t marytts
 - docker run -v /appdir:/appdir -p 8787:8787 -t pronlex /wikispeech/bin/setup /appdir
 - docker run -v /appdir:/appdir -p 8787:8787 -t pronlex &
 - export pronlex_pid=$!
 - echo "pronlex running on pid $pronlex_pid"
 - sleep 20
 - docker run -p 59125:59125 -t marytts &
 - export marytts_pid=$!
 - echo "marytts running on pid $marytts_pid"
 - sleep 20
 - python3 bin/wikispeech docker/config/travis.conf &
 - export wikispeech_pid=$!  
 - echo "wikispeech running on pid $wikispeech_pid"
 - sleep 20
 - sh .travis/exit_server_and_fail_if_not_running.sh wikispeech $wikispeech_pid
 - sh .travis/exit_server_and_fail_if_not_running.sh marytts $marytts_pid
 - sh .travis/exit_server_and_fail_if_not_running.sh pronlex $pronlex_pid
 
